name: Deploy to Server

on:
  push:
    branches:
      - main  # Срабатывает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Переходим в папку с ботом (УКАЖИ СВОЙ ПУТЬ!)
            cd /home/bot/telegram-balance-bot/
            
            # 2. Скачиваем изменения
            git fetch --all
            git reset --hard origin/main
            
            # 3. Активируем виртуальное окружение и обновляем библиотеки (если надо)
            source venv/bin/activate
            pip install -r requirements.txt
            
            # 4. Перезапускаем бота
            sudo systemctl daemon-reload 
            sudo systemctl restart estetico_balance_bot 